FROM docker.io/oracleinanutshell/oracle-xe-11g

MAINTAINER "chachacreate<chachacreate@fz.co.kr>"

# 한글 설정
ENV NLS_LANG=KOREAN_KOREA.AL32UTF8

ADD files/db_table_create.sql /tmp
ADD files/db_user_create.sql /tmp
ADD files/db_init_setting_script.sh /docker-entrypoint-initdb.d/
