FROM docker.io/library/tomcat:9.0.102-jdk11

MAINTAINER "chachacreate<chachacreate@fz.co.kr>"

RUN rm -rf /usr/local/tomcat/webapps/*

EXPOSE 9999 8443

# WAR 압축 해제
RUN mkdir -p /tmp/war
ADD target/ROOT.war /tmp/war/ROOT.war
RUN mkdir /tmp/war/unpacked && cd /tmp/war/unpacked && \
    jar -xf ../ROOT.war

# Tomcat에 직접 복사
RUN mkdir -p /usr/local/tomcat/webapps/ROOT
RUN cp -r /tmp/war/unpacked/* /usr/local/tomcat/webapps/ROOT/

# 디렉토리 생성
RUN mkdir -p /usr/local/tomcat/webapps/ROOT/WEB-INF/classes/properties

# 시간 설정
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime && echo Asia/Seoul > /etc/timezone

ADD files/server.xml /usr/local/tomcat/conf/server.xml
ADD files/ojdbc11-21.9.0.0.jar /usr/local/tomcat/lib/
ADD files/chachacreate.p12 /usr/local/tomcat/ssl/chachacreate.p12
